server:
  port: 5001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
     defaultZone: http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/
  instance:
    hostname: eureka5001.com
    instance-id: eureka5001.com

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:5002/eureka/,http://localhost:5003/eureka/
#  instance:
#    hostname: eureka5001.com
#    instance-id: eureka5001.com

#eureka:
#  client:
#    register-with-eureka: false
#  instance:
#      hostname: eureka5001.com
#      instance-id: eureka5001.com