server:
  port: 6003

spring:
  application:
    name: xydl-robot

#×¢²áµ½eurekaÖĞĞÄ
eureka:
  client:
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/