spring:
 application:
  name: xydl-consumer
server:
 port: 7001
xydl-provider:
 ribbon:
  eureka:
   enabled: false
 listOfServers: localhost:8002,localhost:6002,localhost:6003
 ServerListRefreshInterval: 15000