
server:
  port: 6001

mybatis:
  typeAliasesPackage: com.njit.xydl.life.*.entity
  mapperLocations: classpath:mapper/*/*.xml
  mapperScanPackage: com.njit.xydl.life.*.dao
  configLocation: classpath:mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xydl_life
    username: root
    password: 941012
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: xydl-life

eureka:
  client:
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/