server:
  port: 6003

mybatis:
  typeAliasesPackage: com.njit.xydl.car.entity
  mapperLocations: classpath:mapper/*.xml
  mapperScanPackage: com.njit.xydl.car.dao
  configLocation: classpath:mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xydl_car
    username: root
    password: 941012
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: xydl-car
  redis:
    database: 4
    host: 192.168.43.38
    password: 941012
    port: 6379
    pool:
      jedis:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

#注册到eureka中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/